# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72864a7742226a9931a1d196797dcc29ef65fc1402d3e1627f4fb2fedabecca0ea427be9bdb027393e964cbcfe458c0f117db05c16975ee57eafdb93517aa102

test:
  secret_key_base: 0ec1dd113f846b4772dd0bce7d26c148097a152d99d2c7bdef4544a6cab67aa8410fb42469e87f99089cad4bc11976fcf20e65e096b90a139548edfe0a2c666b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
